Repository dbt-labs/dbt-bigquery, pull requests merged in 2021-11, with the labels that each got.

#53 Change Bigquery google-api-core max version dependency
  CHANGELOG.md
  setup.py
Labels: cla:yes

#48 Fix problem with row access policy doesnt return bytes proccessed.
  CHANGELOG.md
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ok to test

#58 Install dbt-core first
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#57 Bump google dependency upper bounds, remove `six`
  CHANGELOG.md
  setup.py
Labels: cla:yes, test bigquery

#60 Fix tests failing due to dbt-core changes
  tests/integration/docs_generate_tests/test_docs_generate.py
  tests/unit/utils.py
Labels: cla:yes

#59 Rm py36 support + fix failing test
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CHANGELOG.md
  setup.py
  tests/integration/docs_generate_tests/test_docs_generate.py
  tox.ini
Labels: cla:yes

#55 converted to use new struct logging
  CHANGELOG.md
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/gcloud.py
  dbt/adapters/bigquery/impl.py
  tests/integration/base.py
  tests/integration/query_comments_test/test_query_comments.py
Labels: cla:yes

#69 Slack message for failed nightly runs
  .github/workflows/integration.yml
Labels: cla:yes

#66 Adding execution_project to target object
  CHANGELOG.md
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ok to test

#63 Making scopes a configurable profile config option for BigQuery
  CHANGELOG.md
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ok to test

#65 Don't apply `require_partition_filter` to a temporary table
  CHANGELOG.md
  dbt/adapters/bigquery/impl.py
Labels: cla:yes, ok to test
