Repository dbt-labs/dbt-bigquery, pull requests merged in 2022-08, with the labels that each got.

#225 Add job_id/project_id to adapter response to enable easy job linking
  CHANGELOG.md
  dbt/adapters/bigquery/connections.py
  tests/integration/bigquery_test/test_bigquery_adapter_functions.py
Labels: cla:yes, ready_for_review

#249 Revert "Add job_id/project_id to adapter response to enable easy job linking"
  CHANGELOG.md
  dbt/adapters/bigquery/connections.py
  tests/integration/bigquery_test/test_bigquery_adapter_functions.py
Labels: cla:yes

#253 [Feature ] implement changie in dbt-bigquery
  .changes/0.0.0.md
  .changes/1.3.0-b1.md
  .changes/1.3.0/Features-20220804-154944.yaml
  .changes/1.3.0/Features-20220804-155057.yaml
  .changes/1.3.0/Under the Hood-20220804-155219.yaml
  .changes/README.md
  .changes/header.tpl.md
  .changes/unreleased/.gitkeep
  .changes/unreleased/Under the Hood-20220804-155719.yaml
  .changie.yaml
  .github/pull_request_template.md
  .github/workflows/bot-changelog.yml
  .github/workflows/changelog-existence.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: cla:yes

#250 Add job_id/project_id to adapter response to enable easy job linking (fixed)
  .changes/unreleased/Under the Hood-20220806-142912.yaml
  dbt/adapters/bigquery/connections.py
  tests/integration/bigquery_test/test_bigquery_adapter_functions.py
Labels: cla:yes, ok to test, ready_for_review

#261 minor fixes for changie
  .changes/README.md
  .github/pull_request_template.md
  .github/workflows/changelog-existence.yml
Labels: cla:yes, Skip Changelog

#262 Change no issue reference in bot-changelog.yml and add condional logic for kinds
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#276 Fix a typo in `changelog-existence.md`
  .github/workflows/changelog-existence.yml
Labels: cla:yes, Skip Changelog

#282 Shared version-bump and adding backport actions
  .github/workflows/backport.yml
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#290 add supported language
  .changes/unreleased/Under the Hood-20220825-073235.yaml
  dbt/include/bigquery/macros/materializations/incremental.sql
  dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes

#271 Add `slot_ms` to `BigQueryAdapterResponse`
  .changes/unreleased/Under the Hood-20220817-154151.yaml
  dbt/adapters/bigquery/connections.py
  tests/integration/bigquery_test/test_bigquery_adapter_functions.py
Labels: cla:yes

#120 expanding test env example
  test.env.example
Labels: cla:yes, Skip Changelog
