Repository dbt-labs/dbt-bigquery, pull requests merged in 2022-09, with the labels that each got.

#303 Enhancement/enable serverless
  .changes/unreleased/Features-20220909-122924.yaml
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/include/bigquery/macros/materializations/table.sql
  dev-requirements.txt
  tests/conftest.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#304 fix dev-req
  dbt/adapters/bigquery/python_submissions.py
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#305 Make storage and dataproc required Lib and disable unstable test
  dbt/adapters/bigquery/python_submissions.py
  setup.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, Skip Changelog

#295 Update repo templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/ISSUE_TEMPLATE/release.md
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#310 update retry settings experiment
  .changes/unreleased/Under the Hood-20220915-145212.yaml
  dbt/adapters/bigquery/connections.py
  tests/conftest.py
Labels: cla:yes

#301 Convert df to pyspark DataFrame if it is pandas before writing
  .changes/unreleased/Under the Hood-20220908-143218.yaml
  dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes, ready_for_review

#317 Convert df to Spark DataFrame if it is a pandas or pandas-on-Spark DataFrame before writing
  .changes/unreleased/Under the Hood-20220920-151057.yaml
  dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes, ready_for_review

#313 add type boolean
  .changes/unreleased/Features-20220919-232721.yaml
  dbt/adapters/bigquery/column.py
  tests/functional/adapter/utils/test_data_types.py
Labels: cla:yes, Team:Adapters, ready_for_review

#322 Tests for `current_timestamp`
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, Skip Changelog

#308 Array macros
  .changes/unreleased/Features-20220913-084836.yaml
  dbt/include/bigquery/macros/utils/array_append.sql
  dbt/include/bigquery/macros/utils/array_concat.sql
  dbt/include/bigquery/macros/utils/array_construct.sql
  tests/functional/adapter/utils/fixture_array_append.py
  tests/functional/adapter/utils/fixture_array_concat.py
  tests/functional/adapter/utils/fixture_array_construct.py
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, ready_for_review

#321 Convert df to pyspark DataFrame if it is koalas before writing
  .changes/unreleased/Under the Hood-20220924-134858.yaml
  dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes

#318 CT-1166 bigquery conversion of test_alias
  tests/functional/adapter/test_aliases.py
  tests/integration/aliases_test/macros/cast.sql
  tests/integration/aliases_test/macros/expect_value.sql
  tests/integration/aliases_test/models-dupe-custom-database/README.md
  tests/integration/aliases_test/models-dupe-custom-database/model_a.sql
  tests/integration/aliases_test/models-dupe-custom-database/model_b.sql
  tests/integration/aliases_test/models-dupe-custom-database/schema.yml
  tests/integration/aliases_test/models/alias_in_project.sql
  tests/integration/aliases_test/models/alias_in_project_with_override.sql
  tests/integration/aliases_test/models/foo_alias.sql
  tests/integration/aliases_test/models/ref_foo_alias.sql
  tests/integration/aliases_test/models/schema.yml
  tests/integration/aliases_test/test_aliases.py
Labels: cla:yes, Skip Changelog

#252 Update Readme to link to the repository CONTRIBUTING.md
  README.md
Labels: cla:yes, Skip Changelog

#328 try/except rather than find_spec for optional imports
  dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes, Skip Changelog

#323 consolidate timestamps
  .changes/unreleased/Features-20220926-105700.yaml
  dbt/include/bigquery/macros/adapters.sql
  dbt/include/bigquery/macros/utils/timestamps.sql
  tests/functional/adapter/utils/test_timestamps.py
Labels: cla:yes
