Repository dbt-labs/dbt-bigquery, pull requests merged in 2022-10, with the labels that each got.

#338 fix operation wait for cluster submission
  .pre-commit-config.yaml
  dbt/adapters/bigquery/python_submissions.py
  dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes, Skip Changelog

#332 CT-1043 Support google-cloud-bigquery 3.x.x dependency
  .changes/unreleased/Dependencies-20221010-181501.yaml
  setup.py
Labels: cla:yes

#333 [CT-1271] Query Comment test conversion
  tests/functional/adapter/query_comment_test/test_query_comment.py
  tests/integration/query_comments_test/macros/macro.sql
  tests/integration/query_comments_test/models/x.sql
  tests/integration/query_comments_test/test_query_comments.py
Labels: cla:yes, Skip Changelog

#351 migrate changing_relation_type test
  tests/functional/adapter/test_changing_relation_type.py
  tests/integration/changing_relation_type_test/models/model.sql
  tests/integration/changing_relation_type_test/test_changing_relation_type.py
Labels: cla:yes, Skip Changelog

#353 update following changes in CORE#5949
  dbt/adapters/bigquery/impl.py
  tests/integration/sources_test/test_sources.py
Labels: cla:yes, Skip Changelog

#136 Support for ingestion time partition table on BigQuery as incremental materialization
  .changes/unreleased/Features-20220807-164227.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/materializations/incremental.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/merge.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql
  tests/integration/incremental_schema_tests/models/incremental_time_ingestion_partitioning.sql
  tests/integration/incremental_schema_tests/models/incremental_time_ingestion_partitioning_target.sql
  tests/integration/incremental_schema_tests/models/schema.yml
  tests/integration/incremental_schema_tests/test_incremental_schema.py
  tests/integration/incremental_schema_tests/tests/select_from_incremental_time_ingestion_partitioning.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_time_ingestion_partitioning_target.sql
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes, ok to test, ready_for_review

#363 fix args for console link logging
  .changes/unreleased/Fixes-20221026-192327.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ok to test
