Repository dbt-labs/dbt-bigquery, pull requests merged in 2022-12, with the labels that each got.

#382 [CT-1412] test_aliases functional test hanging artifacts
  dbt/adapters/bigquery/column.py
  dbt/adapters/bigquery/impl.py
  tests/functional/adapter/test_aliases.py
Labels: cla:yes, Skip Changelog

#406 [CT-1594] updating workflow
  .changes/unreleased/Under the Hood-20221202-161030.yaml
  .github/workflows/main.yml
Labels: cla:yes

#410 [CT-1405] Bigquery minor changes for event logging
  .changes/unreleased/Under the Hood-20221207-103505.yaml
  tests/integration/base.py
Labels: cla:yes

#411 updating passenv in tox
  .changes/unreleased/Under the Hood-20221207-151813.yaml
  tox.ini
Labels: cla:yes

#417 format fix for tox changes
  tox.ini
Labels: cla:yes, Skip Changelog

#413 [BACKPORT] #411
  .changes/unreleased/Under the Hood-20221207-151813.yaml
  tox.ini
Labels: cla:yes

#420 [BACKPORT] tox passenv spacing changes to 1.1.latest
  tox.ini
Labels: cla:yes, Skip Changelog

#421 [Backport 1.0.latest] updating passenv in tox
  .changes/unreleased/Under the Hood-20221207-151813.yaml
  tox.ini
Labels: cla:yes

#430 add release workflow
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#284 Feature/incremental predicates support
  .changes/unreleased/Features-20220823-085601.yaml
  dbt/include/bigquery/macros/materializations/incremental.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/merge.sql
  tests/functional/adapter/test_incremental_predicates.py
  tests/integration/simple_copy_test/test_simple_copy.py
Labels: cla:yes, Team:Adapters, ready_for_review

#435 swap trigger, update commit sha on release workflow
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#431 dbt-bigquery python 3.11 support
  .changes/unreleased/Dependencies-20221213-135331.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes

#445 [CT-1691] Bug - Partition by validation failing
  .changes/unreleased/Under the Hood-20221221-124711.yaml
  dbt/adapters/bigquery/impl.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes
