Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-07, with the labels that each got.

#803 add clean_up method for store_test_failures tests to stop hanging art…
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
Labels: cla:yes, Skip Changelog, backport 1.5.latest

#813 Update pr template
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#814 fix whitespace change
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#806 Contracts: Handle struct column specified both at root and nested levels + arrays of structs
  .changes/unreleased/Fixes-20230630-213112.yaml
  dbt/adapters/bigquery/column.py
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
  tests/unit/test_column.py
Labels: cla:yes, backport 1.5.latest

#784 add macros and adapter test for new dbt_clone flag
  .changes/unreleased/Features-20230622-113645.yaml
  dbt/include/bigquery/macros/materializations/clone.sql
  tests/functional/adapter/dbt_clone/test_dbt_clone.py
Labels: cla:yes

#819 Add support for validate_sql method to BigQuery
  .changes/unreleased/Features-20230712-014350.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/impl.py
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#812 [BACKPORT] backport teardown_method for test
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
Labels: cla:yes, Skip Changelog

#826 Revert "Add `batch_id` param to profile to pass along with `dataproc_v1.CreateBatchRequest` (#727)"
  .changes/unreleased/Features-20230517-092205.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/python_submissions.py
  test.env.example
  tests/conftest.py
Labels: cla:yes, Skip Changelog

#823 add input to allow testing against a non-main core branch
  .github/scripts/update_dbt_core_branch.sh
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#630 Use tmp table in static insert overwrite
  .changes/unreleased/Fixes-20230325-204352.yaml
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/test_incremental_strategies.py
Labels: cla:yes, ok to test, test_bigquery, test all, ready_for_review, pr_tracked

#829 add datadog env vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#836 [Backport 1.6.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#837 [Backport 1.5.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#835 [Backport 1.4.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#834 [Backport 1.3.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#833 [Backport 1.2.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#844 Update stale workflow to use centralized version
  .changes/unreleased/Under the Hood-20230724-164946.yaml
  .github/workflows/stale.yml
Labels: cla:yes
