Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-06, with the labels that each got.

#698 add tests for rendering foreign key constraints
  .changes/unreleased/Fixes-20230511-143217.yaml
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, backport 1.5.latest

#754 Standardize the adapter for core debug changes.
  .changes/unreleased/Features-20230604-034603.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/impl.py
Labels: cla:yes

#758 change group for env in bigquery
  .github/workflows/integration.yml
  scripts/env-setup.sh
  test.env.example
Labels: cla:yes, Skip Changelog

#760 [BACKPORT] #758 to 1.5.latest
  .github/workflows/integration.yml
  scripts/env-setup.sh
  test.env.example
Labels: cla:yes, Skip Changelog

#762 [BACKPORT] #758 to 1.3.latest
  .github/workflows/integration.yml
  .github/workflows/nightly-release.yml
  scripts/env-setup.sh
  test.env.example
Labels: cla:yes, Skip Changelog

#763 [BACKPORT] #758 to 1.2.latest
  .github/workflows/integration.yml
  .github/workflows/nightly-release.yml
  scripts/env-setup.sh
  test.env.example
Labels: cla:yes, Skip Changelog

#764 [BACKPORT] #758 to 1.1.latest and change nightly release pointer
  .github/workflows/nightly-release.yml
  scripts/env-setup.sh
  test.env.example
Labels: cla:yes, Skip Changelog

#761 [BACKPORT] #758 to 1.4.latest
  .github/workflows/integration.yml
  scripts/env-setup.sh
  test.env.example
Labels: cla:yes, Skip Changelog

#765 [Backport] 698 to 1.5.latest
  .changes/unreleased/Fixes-20230511-143217.yaml
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#756 Backport/1.0.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#713 Test constraint rendering with column quoting
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#738 model contracts + constraints with nested fields
  .changes/unreleased/Features-20230601-141255.yaml
  dbt/adapters/bigquery/column.py
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
  tests/functional/adapter/constraints/fixtures.py
  tests/functional/adapter/constraints/test_constraints.py
  tests/unit/test_column.py
Labels: cla:yes, backport 1.5.latest

#771 Test constraint rendering with column quoting (#713)
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#772 [Backport] model contracts + constraints with nested fields (#738)
  .changes/unreleased/Features-20230601-141255.yaml
  dbt/adapters/bigquery/column.py
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
  tests/functional/adapter/constraints/fixtures.py
  tests/functional/adapter/constraints/test_constraints.py
  tests/unit/test_column.py
Labels: cla:yes

#776 add dependent_projects_dict to utils.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#778 Rm agate as explicit dep
  .changes/unreleased/Dependencies-20230618-220517.yaml
  setup.py
Labels: cla:yes

#779 backport 742 to 1.5.latest
  .changes/unreleased/Breaking Changes-20230530-174051.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes

#766 Pass python model timeout to polling instead of retry
  .changes/unreleased/Fixes-20230609-132727.yaml
  dbt/adapters/bigquery/python_submissions.py
  tests/functional/adapter/test_python_model.py
  tox.ini
Labels: cla:yes

#750 add sql_header tests for constraints
  .changes/unreleased/Fixes-20230601-120430.yaml
  tests/functional/adapter/constraints/test_constraints.py
Labels: cla:yes

#727 Add `batch_id` param to profile to pass along with `dataproc_v1.CreateBatchRequest`
  .changes/unreleased/Features-20230517-092205.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/python_submissions.py
  test.env.example
  tests/conftest.py
Labels: cla:yes, ready_for_review

#791 Avoid unnecessary grant call
  .changes/unreleased/Fixes-20230626-105156.yaml
  dbt/adapters/bigquery/dataset.py
  dbt/adapters/bigquery/impl.py
  tests/unit/test_dataset.py
Labels: cla:yes

#794 [Backport 1.4.latest] Dropping support for py37 (#742)
  .changes/unreleased/Breaking Changes-20230530-174051.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes

#795 [Backport 1.3.latest] Dropping support for py37 (#742)
  .changes/unreleased/Breaking Changes-20230530-174051.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.md
  setup.py
  tox.ini
Labels: cla:yes

#797 [Backport 1.1.latest] Dropping support for py37 (#742)
  .changes/unreleased/Breaking Changes-20230530-174051.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.md
  setup.py
  tox.ini
Labels: cla:yes

#798 [Backport 1.0.latest] Dropping support for py37 (#742)
  .changes/unreleased/Breaking Changes-20230530-174051.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.md
  setup.py
  tox.ini
Labels: cla:yes

#697 move job link logging just after the job submit
  .changes/unreleased/Features-20230505-184427.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ready_for_review, pr_tracked

#800 Remove dependent_projects argument from PartialProject call in unit tests
  .changes/unreleased/Fixes-20230628-162853.yaml
  tests/unit/utils.py
Labels: cla:yes

#802 add thread_id to seeds for hooks tests to fix failure caused by change in core
  tests/functional/adapter/hooks/data/seed_model.sql
  tests/functional/adapter/hooks/data/seed_run.sql
Labels: cla:yes, Skip Changelog
