Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-04, with the labels that each got.

#655 Update `bigquery__format_column` per dbt-core#7319
  .changes/unreleased/Under the Hood-20230411-143129.yaml
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
Labels: cla:yes

#648 Model-Level Constraints
  .changes/unreleased/Features-20230406-104433.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/adapters.sql
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
  dev-requirements.txt
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#658 Repair accidental change to dev-requirements
  .changes/unreleased/Fixes-20230411-143515.yaml
  dev-requirements.txt
Labels: cla:yes

#646 update for generalized constraint warnings
  .changes/1.5.0/Features-20221220-193731.yaml
  dbt/adapters/bigquery/impl.py
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#653 add steps to drop existing tables on --full-refresh
  .changes/unreleased/Fixes-20230408-035117.yaml
  dbt/include/bigquery/macros/adapters.sql
Labels: cla:yes, backport 1.4.latest

#552 Ignore nulls in partitions to be processed
  .changes/unreleased/Fixes-20230222-133301.yaml
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
Labels: cla:yes, ready_for_review, pr_tracked

#651 [ADAP-17]: Test conversion for simple snapshot into a functional test
  tests/functional/adapter/test_simple_snaphot.py
  tests/integration/__init__.py
  tests/integration/base.py
  tests/integration/simple_snapshot_test/add_column_to_source_bq.sql
  tests/integration/simple_snapshot_test/check-snapshots-expected/check_snapshots_test_current.sql
  tests/integration/simple_snapshot_test/check-snapshots/check_cols_cycle.sql
  tests/integration/simple_snapshot_test/custom-snapshot-macros/custom.sql
  tests/integration/simple_snapshot_test/invalidate_bigquery.sql
  tests/integration/simple_snapshot_test/macros/test_no_overlaps.sql
  tests/integration/simple_snapshot_test/models/.gitkeep
  tests/integration/simple_snapshot_test/models/ref_snapshot.sql
  tests/integration/simple_snapshot_test/models/schema.yml
  tests/integration/simple_snapshot_test/seed.sql
  tests/integration/simple_snapshot_test/seed_bq.sql
  tests/integration/simple_snapshot_test/seeds/seed.csv
  tests/integration/simple_snapshot_test/seeds/seed_newcol.csv
  tests/integration/simple_snapshot_test/test-check-col-snapshots-bq/snapshot.sql
  tests/integration/simple_snapshot_test/test-check-col-snapshots-noconfig/snapshot.sql
  tests/integration/simple_snapshot_test/test-check-col-snapshots/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-bq/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-checkall/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-pg/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-select-noconfig/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-select/snapshot.sql
  tests/integration/simple_snapshot_test/test_simple_snapshot.py
  tests/integration/simple_snapshot_test/test_snapshot_check_cols.py
  tests/integration/simple_snapshot_test/update_bq.sql
Labels: cla:yes, Skip Changelog

#667 1.5.0rc1 changelog
  .changes/1.5.0-b1.md
  .changes/1.5.0-b2.md
  .changes/1.5.0-b3.md
  .changes/1.5.0-b4.md
  .changes/1.5.0-rc1.md
  .changes/1.5.0/Features-20230406-104433.yaml
  .changes/1.5.0/Fixes-20230222-133301.yaml
  .changes/1.5.0/Fixes-20230408-035117.yaml
  .changes/1.5.0/Fixes-20230411-143515.yaml
  .changes/1.5.0/Under the Hood-20230411-143129.yaml
Labels: cla:yes, Skip Changelog

#669 Fix CHANGELOG.md for 1.5.0rc1
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#663 Adap 444/reformat the repo to precommit hooks
  .pre-commit-config.yaml
  dbt/adapters/bigquery/impl.py
  tests/conftest.py
  tests/functional/adapter/column_types/test_alter_column_types.py
  tests/functional/adapter/column_types/test_column_types.py
  tests/functional/adapter/hooks/test_model_hooks.py
  tests/functional/adapter/hooks/test_run_hooks.py
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/seeds.py
  tests/functional/adapter/incremental/test_incremental_merge_exclude_columns.py
  tests/functional/adapter/incremental/test_incremental_on_schema_change.py
  tests/functional/adapter/incremental/test_incremental_predicates.py
  tests/functional/adapter/incremental/test_incremental_strategies.py
  tests/functional/adapter/incremental/test_incremental_unique_id.py
  tests/functional/adapter/query_comment_test/test_query_comment.py
  tests/functional/adapter/simple_bigquery_view/fixtures.py
  tests/functional/adapter/simple_bigquery_view/seeds.py
  tests/functional/adapter/simple_bigquery_view/test_simple_bigquery_view.py
  tests/functional/adapter/simple_copy/test_simple_copy.py
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
  tests/functional/adapter/test_aliases.py
  tests/functional/adapter/test_changing_relation_type.py
  tests/functional/adapter/test_constraints.py
  tests/functional/adapter/test_dbt_debug.py
  tests/functional/adapter/test_grant_access_to.py
  tests/functional/adapter/test_grants.py
  tests/functional/adapter/test_persist_docs.py
  tests/functional/adapter/test_python_model.py
  tests/functional/adapter/test_simple_seed.py
  tests/functional/adapter/test_simple_snaphot.py
  tests/functional/adapter/upload_file_tests/data/ndjson/source.ndjson
  tests/functional/adapter/upload_file_tests/test_upload_file.py
  tests/functional/adapter/utils/test_data_types.py
  tests/functional/adapter/utils/test_timestamps.py
  tests/functional/adapter/utils/test_utils.py
  tests/functional/test_changing_partitions.py
  tests/functional/test_delete_column_policy.py
  tests/functional/test_get_columns_incomplete_database.py
  tests/functional/test_hours_to_expiration.py
  tests/functional/test_incremental_materialization.py
  tests/functional/test_location_change.py
  tests/functional/test_override_database/fixtures.py
  tests/functional/test_override_database/test_override_database.py
  tests/functional/test_update_column_policy.py
  tests/functional/test_update_field_description.py
  tests/unit/mock_adapter.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_configure_dataproc_batch.py
  tests/unit/test_dataset.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#674 ADAP-382: Address TestAccessGrantSucceeds sporadic failure
  .changes/unreleased/Fixes-20230421-120450.yaml
  tests/functional/adapter/test_grant_access_to.py
Labels: cla:yes, backport 1.4.latest, backport 1.5.latest

#676 ADAP-382: Address TestAccessGrantSucceeds sporadic failure (#674)
  .changes/unreleased/Fixes-20230421-120450.yaml
  tests/functional/adapter/test_grant_access_to.py
Labels: cla:yes

#496 Support all types of data_type using time ingestion partitioning
  .changes/unreleased/Fixes-20230202-010912.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/adapters.sql
  dbt/include/bigquery/macros/materializations/incremental.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/merge.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/test_incremental_strategies.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes, ok to test, test_bigquery, test all, ready_for_review, pr_tracked

#683 Fix UDF usage with time ingestion
  .changes/unreleased/Fixes-20230427-141957.yaml
  dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
Labels: cla:yes, ok to test, test_bigquery, test all
