Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-03, with the labels that each got.

#572 Ct 2183/setup tools distro info
  .flake8
  .pre-commit-config.yaml
  Makefile
  dbt/adapters/bigquery/impl.py
  dev-requirements.txt
Labels: cla:yes, Skip Changelog, backport 1.4.latest

#574 Revert "Revert "mirror issues to ADAP jira project""
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes

#485 Fix time ingestion partitioning option regression
  .changes/unreleased/Fixes-20230202-010332.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
  tests/functional/adapter/bigquery_test/test_incremental_strategies.py
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/seeds.py
  tests/functional/adapter/incremental/test_incremental_strategies.py
  tests/functional/adapter/simple_bigquery_view/fixtures.py
  tests/functional/adapter/simple_bigquery_view/seeds.py
  tests/functional/adapter/simple_bigquery_view/test_simple_bigquery_view.py
Labels: cla:yes, ok to test, ready_for_review, pr_tracked

#573 Backport 572 to 1.4.latest
  .dockerignore
  .flake8
  .pre-commit-config.yaml
  Makefile
  dbt/adapters/bigquery/impl.py
  dev-requirements.txt
  docker_dev/README.md
  docker_dev/ubuntu.Dockerfile
  setup.py
Labels: cla:yes, Skip Changelog

#551 implement get_column_schema_from_query
  .changes/unreleased/Features-20230223-145508.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#591 backport 485 to 1.4.latest
  .changes/unreleased/Fixes-20230202-010332.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/seeds.py
  tests/functional/adapter/incremental/test_incremental_strategies.py
  tests/functional/adapter/simple_bigquery_view/fixtures.py
  tests/functional/adapter/simple_bigquery_view/seeds.py
  tests/functional/adapter/simple_bigquery_view/test_simple_bigquery_view.py
Labels: cla:yes

#584 support contracts on models materialized as view
  .changes/unreleased/Features-20230223-145508.yaml
  dbt/include/bigquery/macros/adapters.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#582 add new scripts for cut-release workflow
  .github/scripts/update_dependencies.sh
  .github/scripts/update_release_branch.sh
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#578 Dataproc config for serverless in profile and fix quoting
  .changes/unreleased/Features-20230303-132509.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/include/bigquery/macros/python_model/python.sql
  dev-requirements.txt
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_configure_dataproc_batch.py
  tox.ini
Labels: cla:yes

#563 Update connections.py with retry logic for 502
  .changes/unreleased/Fixes-20230227-110426.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ready_for_review, pr_tracked

#593 Remove 3.9 from main workflow
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  tox.ini
Labels: cla:yes, Skip Changelog

#598 backport pr #578
  .changes/unreleased/Features-20230303-132509.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/include/bigquery/macros/python_model/python.sql
  dev-requirements.txt
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_configure_dataproc_batch.py
  tox.ini
Labels: cla:yes

#594 [ADAP-353]: Fix for #581: Python incremental model
  .changes/unreleased/Fixes-20230309-181313.yaml
  dbt/include/bigquery/macros/materializations/incremental.sql
  tests/functional/adapter/test_python_model.py
  tox.ini
Labels: cla:yes

#600 backport PR #594 to 1.4.latest
  .changes/unreleased/Fixes-20230309-181313.yaml
  dbt/include/bigquery/macros/materializations/incremental.sql
  tests/functional/adapter/test_python_model.py
  tox.ini
Labels: cla:yes

#601 add triage-labels workflow
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#542 Allow column policy_tags to be removed by removing them from model
  .changes/unreleased/Fixes-20230216-140756.yaml
  dbt/adapters/bigquery/impl.py
  tests/functional/test_delete_column_policy.py
Labels: cla:yes, ready_for_review, pr_tracked

#607 Remove checks on non-leaf-field tags since they no longer can exist.
  .changes/unreleased/Fixes-20230315-130504.yaml
  tests/functional/adapter/test_persist_docs.py
Labels: cla:yes

#610 Backport PR 607 manually to 1.1.latest.
  .changes/unreleased/Fixes-20230315-130504.yaml
  tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml
  tests/integration/persist_docs_tests/test_persist_docs.py
Labels: cla:yes

#611 Backport PR 607 manually to 1.2.latest.
  .changes/unreleased/Fixes-20230315-130504.yaml
  tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml
  tests/integration/persist_docs_tests/test_persist_docs.py
Labels: cla:yes

#612 Backport/605 to 1.3.latest
  .changes/unreleased/Fixes-20230315-130504.yaml
  tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml
  tests/integration/persist_docs_tests/test_persist_docs.py
Labels: cla:yes

#613 Backport/605 manually to 1.4.latest
  .changes/unreleased/Fixes-20230315-130504.yaml
  tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml
  tests/integration/persist_docs_tests/test_persist_docs.py
Labels: cla:yes

#570 Add `bytes_billed` to `BigQueryAdapterResponse`
  .changes/unreleased/Features-20230228-094234.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ready_for_review, pr_tracked

#606 Use contract column order in create table
  .changes/unreleased/Features-20230315-120554.yaml
  dbt/include/bigquery/macros/adapters.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#603 Modify adapter to support unified constraint fields
  .changes/unreleased/Features-20230314-171221.yaml
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#622 Use _make_ref_key_dict instead of _make_ref_key_msg
  .changes/unreleased/Fixes-20230322-162200.yaml
  dbt/adapters/bigquery/impl.py
Labels: cla:yes

#620 Adap 13/simple copy test conversion
  tests/functional/adapter/simple_copy/fixtures.py
  tests/functional/adapter/simple_copy/test_simple_copy.py
  tests/integration/simple_copy_test/models-merge-update/incremental_update_cols.sql
  tests/integration/simple_copy_test/models/advanced_incremental.sql
  tests/integration/simple_copy_test/models/compound_sort.sql
  tests/integration/simple_copy_test/models/disabled.sql
  tests/integration/simple_copy_test/models/empty.sql
  tests/integration/simple_copy_test/models/get_and_ref.sql
  tests/integration/simple_copy_test/models/incremental.sql
  tests/integration/simple_copy_test/models/interleaved_sort.sql
  tests/integration/simple_copy_test/models/materialized.sql
  tests/integration/simple_copy_test/models/schema.yml
  tests/integration/simple_copy_test/models/view_model.sql
  tests/integration/simple_copy_test/seed-initial/seed.csv
  tests/integration/simple_copy_test/seed-update/seed.csv
  tests/integration/simple_copy_test/seeds-merge-cols-initial/seed.csv
  tests/integration/simple_copy_test/seeds-merge-cols-update/expected_result.csv
  tests/integration/simple_copy_test/seeds-merge-cols-update/seed.csv
  tests/integration/simple_copy_test/test_simple_copy.py
  tests/integration/statement_test/models-bq/statement_actual.sql
  tests/integration/statement_test/seed/seed.csv
  tests/integration/statement_test/seed/statement_expected.csv
  tests/integration/statement_test/test_statements.py
Labels: cla:yes, Skip Changelog

#623 See about adding dev requirements to test runner
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#628 Fix test
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes, Skip Changelog

#608 add test for enforcing contracts on incremental materializations
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#634 update to retrieve contract enforced from dict
  .changes/1.5.0/Under the Hood-20230223-105149.yaml
  .changes/unreleased/Under the Hood-20230223-105149.yaml
  dbt/include/bigquery/macros/adapters.sql
Labels: cla:yes
