Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-11, with the labels that each got.

#1004 Support agate Integer type, test with empty seed
  .changes/unreleased/Fixes-20231107-100905.yaml
  dbt/adapters/bigquery/impl.py
  tests/functional/adapter/test_simple_seed.py
  tests/unit/mock_adapter.py
Labels: cla:yes

#1009 ADAP-1017: Fix configuration change monitoring for scenarios with no changes
  .changes/unreleased/Fixes-20231107-174352.yaml
  dbt/adapters/bigquery/relation.py
  dbt/adapters/bigquery/relation_configs/_partition.py
  tests/functional/adapter/materialized_view_tests/_files.py
  tests/functional/adapter/materialized_view_tests/test_materialized_view.py
Labels: cla:yes, backport 1.7.latest

#991 Fix inline comments (--) on the last line of an incremental model (partition replacement)
  .changes/unreleased/Fixes-20231105-125740.yaml
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
Labels: cla:yes, ok to test

#1014 Fix Broken Python Models
  .changes/unreleased/Fixes-20231108-171128.yaml
  .changes/unreleased/Under the Hood-20231109-095012.yaml
  .github/workflows/integration.yml
  dbt/adapters/bigquery/dataproc/batch.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/include/bigquery/macros/materializations/table.sql
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#1020 fix 409 duplicate batch issue
  .changes/unreleased/Fixes-20231111-150959.yaml
  dbt/adapters/bigquery/python_submissions.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes
