Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-08, with the labels that each got.

#845 avoid creating twice the temp table in dynamic insert overwrite
  .changes/unreleased/Fixes-20230727-213526.yaml
  dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
  tests/functional/adapter/incremental/test_incremental_on_schema_change.py
Labels: cla:yes, ok to test

#852 Requiring Python >=3.8 enables walrus operator
  .changes/unreleased/Fixes-20230803-102915.yaml
  setup.py
Labels: cla:yes, ready_for_review, backport 1.0.latest, backport 1.1.latest, backport 1.2.latest, backport 1.3.latest, backport 1.4.latest, backport 1.5.latest, backport 1.6.latest

#859 Move Alerts
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#875 add env vars for datadog test visibility
  tox.ini
Labels: cla:yes, Skip Changelog

#804 Swap dataproc `batch_id` declaration to model config
  .changes/unreleased/Fixes-20230630-092618.yaml
  dbt/adapters/bigquery/python_submissions.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, ok to test, ready_for_review

#879 [Backport 1.3.latest] add env vars for datadog test visibility
  tox.ini
Labels: cla:yes, Skip Changelog

#890 change type of expected value
  .changes/unreleased/Fixes-20230821-180758.yaml
  tests/functional/adapter/expected_stats.py
Labels: cla:yes

#888 case insensitive check on partition matching
  .changes/unreleased/Fixes-20230818-214616.yaml
  dbt/adapters/bigquery/__init__.py
  dbt/adapters/bigquery/impl.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes, ok to test, ready_for_review

#892 [BACKPORT] ADAP-834 case insensitive check on partition matching (#888)
  .changes/unreleased/Fixes-20230818-214616.yaml
  dbt/adapters/bigquery/__init__.py
  dbt/adapters/bigquery/impl.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes, Skip Changelog

#894 revert change made in pr 890 to go along with core revert
  .changes/unreleased/Fixes-20230821-180758.yaml
  tests/functional/adapter/expected_stats.py
Labels: cla:yes, Skip Changelog

#901 [ADAP-851] remove some connection fields that may be sensitive user information …
  dbt/adapters/bigquery/connections.py
Labels: Skip Changelog

#904 ADAP-842: Reformat macro file structure to be more modular and organizaed
  .changes/unreleased/Under the Hood-20230829-122918.yaml
  dbt/include/bigquery/macros/adapters.sql
  dbt/include/bigquery/macros/relations/cluster.sql
  dbt/include/bigquery/macros/relations/drop.sql
  dbt/include/bigquery/macros/relations/options.sql
  dbt/include/bigquery/macros/relations/partition.sql
  dbt/include/bigquery/macros/relations/rename.sql
  dbt/include/bigquery/macros/relations/table/options.sql
  dbt/include/bigquery/macros/relations/view/options.sql
Labels: cla:yes

#905 Fix Dataclass validation logic
  .changes/unreleased/Under the Hood-20230830-160707.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes
