Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-01, with the labels that each got.

#442 truncate sanitized query labels to 63 characters
  .changes/unreleased/Under the Hood-20221219-212421.yaml
  dbt/adapters/bigquery/connections.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes

#230 retry transient connection errors
  .changes/unreleased/Under the Hood-20220805-165120.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#458 fix whitespace issue with incremental sql
  .changes/unreleased/Fixes-20230109-105325.yaml
  .github/workflows/main.yml
  dbt/include/bigquery/macros/materializations/incremental_strategy/merge.sql
  setup.py
  tests/functional/test_incremental_materialization.py
Labels: cla:yes

#456 take over of PR #174 to get changelog in order to merge
  .changes/unreleased/Features-20230109-105921.yaml
  dbt/include/bigquery/macros/catalog.sql
Labels: cla:yes

#461 fix release.yml pypi steps
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#460 update exception names
  .changes/unreleased/Under the Hood-20230110-110016.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/gcloud.py
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/relation.py
  tests/integration/schema_tests_test/test_schema_v2_tests.py
  tests/integration/simple_snapshot_test/test_simple_snapshot.py
  tests/integration/sources_test/test_sources.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes

#467 add 1.3 and 1.4 to testing matrix
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#469 Convert incremental on_schema_change tests
  tests/functional/adapter/incremental/test_incremental_on_schema_change.py
  tests/functional/adapter/incremental/test_incremental_predicates.py
  tests/functional/adapter/incremental/test_incremental_unique_id.py
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one_target.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_target.sql
  tests/integration/incremental_schema_tests/models/incremental_fail.sql
  tests/integration/incremental_schema_tests/models/incremental_ignore.sql
  tests/integration/incremental_schema_tests/models/incremental_ignore_target.sql
  tests/integration/incremental_schema_tests/models/incremental_sync_all_columns.sql
  tests/integration/incremental_schema_tests/models/incremental_sync_all_columns_dynamic_insert_overwrite.sql
  tests/integration/incremental_schema_tests/models/incremental_sync_all_columns_target.sql
  tests/integration/incremental_schema_tests/models/incremental_time_ingestion_partitioning.sql
  tests/integration/incremental_schema_tests/models/incremental_time_ingestion_partitioning_target.sql
  tests/integration/incremental_schema_tests/models/model_a.sql
  tests/integration/incremental_schema_tests/models/schema.yml
  tests/integration/incremental_schema_tests/test_incremental_schema.py
  tests/integration/incremental_schema_tests/tests/select_from_a.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one_target.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_target.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_ignore.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_ignore_target.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_sync_all_columns.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_sync_all_columns_target.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_time_ingestion_partitioning.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_time_ingestion_partitioning_target.sql
Labels: cla:yes, Skip Changelog

#473 Remove test for CT-1629 in dbt-core.
  tests/integration/column_quoting/models-unquoted/model.sql
  tests/integration/column_quoting/models/model.sql
  tests/integration/column_quoting/seeds/seed.csv
  tests/integration/column_quoting/test_column_quotes.py
Labels: cla:yes, Skip Changelog

#479 remove sources integration tests
  tests/integration/sources_test/error_models/model.sql
  tests/integration/sources_test/error_models/schema.yml
  tests/integration/sources_test/filtered_models/schema.yml
  tests/integration/sources_test/macros/macro.sql
  tests/integration/sources_test/malformed_models/descendant_model.sql
  tests/integration/sources_test/malformed_models/schema.yml
  tests/integration/sources_test/malformed_schema_tests/model.sql
  tests/integration/sources_test/malformed_schema_tests/schema.yml
  tests/integration/sources_test/models/descendant_model.sql
  tests/integration/sources_test/models/ephemeral_model.sql
  tests/integration/sources_test/models/multi_source_model.sql
  tests/integration/sources_test/models/nonsource_descendant.sql
  tests/integration/sources_test/models/schema.yml
  tests/integration/sources_test/models/view_model.sql
  tests/integration/sources_test/seed.sql
  tests/integration/sources_test/seeds/expected_multi_source.csv
  tests/integration/sources_test/seeds/other_source_table.csv
  tests/integration/sources_test/seeds/other_table.csv
  tests/integration/sources_test/seeds/source.csv
  tests/integration/sources_test/test_sources.py
Labels: cla:yes, Skip Changelog

#476 [CT-1630] Convert column_types test for dbt-bigquery
  tests/functional/adapter/column_types/fixtures.py
  tests/functional/adapter/column_types/test_alter_column_types.py
  tests/functional/adapter/column_types/test_column_types.py
  tests/integration/column_type_tests/bq_models/model.sql
  tests/integration/column_type_tests/bq_models/schema.yml
  tests/integration/column_type_tests/bq_models_alter_type/altered_schema.yml
  tests/integration/column_type_tests/bq_models_alter_type/model.sql
  tests/integration/column_type_tests/macros/test_alter_column_type.sql
  tests/integration/column_type_tests/macros/test_is_type.sql
  tests/integration/column_type_tests/test_alter_column_types.py
  tests/integration/column_type_tests/test_column_types.py
Labels: cla:yes, Skip Changelog

#466 [CI/CD] Update release workflow and introduce workflow for nightly releases
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#484 Deleted redundant tests
  tests/integration/bigquery_test/copy-models/additional.sql
  tests/integration/bigquery_test/copy-models/copy_as_incremental.sql
  tests/integration/bigquery_test/copy-models/copy_as_several_tables.sql
  tests/integration/bigquery_test/copy-models/copy_as_table.sql
  tests/integration/bigquery_test/copy-models/original.sql
  tests/integration/bigquery_test/copy-models/schema.yml
  tests/integration/bigquery_test/execution-project-models/model.sql
  tests/integration/bigquery_test/execution-project-models/schema.yml
  tests/integration/bigquery_test/test_bigquery_adapter_functions.py
  tests/integration/bigquery_test/test_bigquery_copy_models.py
  tests/integration/bigquery_test/test_bigquery_execution_project.py
  tests/integration/bigquery_test/test_bigquery_query_results.py
  tests/integration/bigquery_test/test_bigquery_repeated_records.py
Labels: cla:yes, Skip Changelog

#497 [CI/CD] Update release workflow definition
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#494 remove case sensitive and copy fail integ tests
  tests/integration/bigquery_test/case-sensitive-models/fUnKyCaSe.sql
  tests/integration/bigquery_test/case-sensitive-schemas/model.sql
  tests/integration/bigquery_test/copy-failing-models/copy_bad_materialization.sql
  tests/integration/bigquery_test/copy-failing-models/original.sql
  tests/integration/bigquery_test/test_bigquery_case_sensitive.py
  tests/integration/bigquery_test/test_bigquery_copy_failing_models.py
Labels: cla:yes, Skip Changelog

#488 convert update columns tests
  tests/functional/test_update_column_policy.py
  tests/functional/test_update_field_description.py
  tests/integration/bigquery_test/test_bigquery_update_columns.py
  tests/integration/bigquery_test/update-column-description/description_table.sql
  tests/integration/bigquery_test/update-column-description/description_table.yml
  tests/integration/bigquery_test/update-column-policy-tag/policy_tag_table.sql
  tests/integration/bigquery_test/update-column-policy-tag/policy_tag_table.yml
Labels: cla:yes, Skip Changelog

#482 Use IEC standard abbreviations (GiB, TiB, etc)
  .changes/unreleased/Fixes-20230125-174159.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ready_for_review

#480 Remove PR requirement from Changelog
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#495 Migrate test and use adapter zone base classes.
  tests/functional/adapter/test_persist_docs.py
  tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml
  tests/integration/persist_docs_tests/models-bigquery-nested/table_model_nested.sql
  tests/integration/persist_docs_tests/models-bigquery-nested/view_model_nested.sql
  tests/integration/persist_docs_tests/models-column-missing/missing_column.sql
  tests/integration/persist_docs_tests/models-column-missing/schema.yml
  tests/integration/persist_docs_tests/models/my_fun_docs.md
  tests/integration/persist_docs_tests/models/no_docs_model.sql
  tests/integration/persist_docs_tests/models/schema.yml
  tests/integration/persist_docs_tests/models/table_model.sql
  tests/integration/persist_docs_tests/models/view_model.sql
  tests/integration/persist_docs_tests/seeds/seed.csv
Labels: cla:yes, Skip Changelog
