Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-10, with the labels that each got.

#955 [fix] Use rendered query comment for job labels
  .changes/unreleased/Fixes-20231005-235950.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/adapter/query_comment_test/test_job_label.py
Labels: cla:yes, ok to test, ready_for_review

#957 a slight rework of 955 to keep a seperation of concerns
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, Skip Changelog

#961 test against 1.7.latest release branch and fix semver
  .github/workflows/nightly-release.yml
Labels: cla:yes, Skip Changelog

#954 Use branch 8007-contract_type_aliasing
  .changes/unreleased/Under the Hood-20231005-115800.yaml
  dbt/adapters/bigquery/column.py
  tests/functional/adapter/constraints/test_constraints.py
Labels: cla:yes

#910 Fix bigquery copy materialization
  .changes/unreleased/Fixes-20230906-141819.yaml
  dbt/include/bigquery/macros/materializations/copy.sql
  tests/functional/adapter/test_copy_materialization.py
Labels: cla:yes, ok to test, ready_for_review

#962 ADAP-940: Add change monitoring for partitioning clause
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/relation.py
  dbt/adapters/bigquery/relation_configs/_base.py
  dbt/adapters/bigquery/relation_configs/cluster.py
  dbt/adapters/bigquery/relation_configs/materialized_view.py
  dbt/adapters/bigquery/relation_configs/options.py
  dbt/adapters/bigquery/relation_configs/partition.py
  dbt/include/bigquery/macros/relation_components/partition/describe.sql
  dbt/include/bigquery/macros/relations/materialized_view/alter.sql
  dbt/include/bigquery/macros/relations/materialized_view/describe.sql
  tests/functional/adapter/describe_relation/_files.py
  tests/functional/adapter/describe_relation/test_describe_relation.py
  tests/functional/adapter/materialized_view_tests/_files.py
  tests/functional/adapter/materialized_view_tests/_mixin.py
  tests/functional/adapter/materialized_view_tests/test_materialized_view_changes.py
Labels: cla:yes

#681 [ADAP-492] Support partition_by and cluster_by on python models (#680)
  .changes/unreleased/Features-20230426-152526.yaml
  dbt/include/bigquery/macros/materializations/table.sql
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, ok to test, ready_for_review, pr_tracked

#882 Remove impersonation lifetime.
  .changes/unreleased/Fixes-20230817-095527.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, ok to test, ready_for_review

#932 ADAP-892: Support test results as views
  .changes/unreleased/Features-20230921-175106.yaml
  Makefile
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
Labels: cla:yes

#943 Add tests for `date_spine` macro, and sub macros
  tests/functional/adapter/utils/fixture_get_intervals_between.py
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, Skip Changelog

#968 add docs-issue workflow to dbt-bigquery
  .github/workflows/docs-issue.yml
Labels: cla:yes, Skip Changelog

#974 Patch for `dbt show` for a model with a `struct` column containing a `json` datatype
  .changes/unreleased/Fixes-20231023-082312.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes, ready_for_review

#980 Lower bound of `2.11.0` for `google-api-core`
  .changes/unreleased/Fixes-20231025-131907.yaml
  setup.py
Labels: cla:yes, test all

#983 Fix refresh syntax, config comparison with empty labels
  .changes/unreleased/Fixes-20231025-223003.yaml
  dbt/adapters/bigquery/relation_configs/_options.py
  dbt/include/bigquery/macros/relations/materialized_view/refresh.sql
Labels: cla:yes

#996 ADAP-972: Fix issue where materialized views were being mapped as tables in catalog queries
  .changes/unreleased/Fixes-20231030-222134.yaml
  dbt/include/bigquery/macros/catalog.sql
  tests/functional/adapter/catalog_tests/files.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
Labels: bug, cla:yes, backport 1.7.latest
