Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-05, with the labels that each got.

#688 Fixes adding policy tags when a struct is defined in the yml
  .changes/unreleased/Fixes-20230428-232904.yaml
  dbt/adapters/bigquery/impl.py
  tests/functional/test_delete_column_policy.py
Labels: cla:yes

#694 Revert PR 607
  tests/functional/adapter/test_persist_docs.py
Labels: cla:yes, Skip Changelog, backport 1.1.latest, backport 1.2.latest, backport 1.3.latest, backport 1.4.latest, backport 1.5.latest

#695 update used gh actions ahead of set-output, node12 deprecation
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#701 Backport #688 to 1.5.latest
  .changes/unreleased/Fixes-20230508-163251.yaml
  dbt/adapters/bigquery/impl.py
  tests/functional/test_delete_column_policy.py
Labels: cla:yes

#707 Add limit to execute signature for consistency with dbt-core
  .changes/unreleased/Fixes-20230509-222705.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#725 updating set-output
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#721 [Backport] 1.1.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#722 [Backport] 1.2.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#719 [Backport] 1.4.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#724 [Backport] 1.5.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#729 update used gh actions ahead of node12 deprecation
  .github/workflows/backport.yml
  .github/workflows/bot-changelog.yml
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#739 [Fix] small change to test pathing for assert clause
  tests/functional/adapter/upload_file_tests/test_upload_file.py
Labels: cla:yes, Skip Changelog

#741 Fix workflow branch
  .github/workflows/release-branch-tests.yml
Labels: Skip Changelog

#742 Drop support for py37
  .changes/unreleased/Breaking Changes-20230530-174051.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes

#740 adding link to 1.5 release notes
  .changes/0.0.0.md
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#744 remove unneeded install of core
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#748 [BACKPORT] remove unneeded install of core (#744)
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#746 [BACKPORT] remove unneeded install of core (#744)
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#745 [BACKPORT] remove unneeded install of core (#744)
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog
