Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-02, with the labels that each got.

#503 [BACKPORT] Remove PR requirement from Changelog (#480)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#504 [BACKPORT] Remove PR requirement from Changelog (#480)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#505 [BACKPORT] Remove PR requirement from Changelog (#480)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#506 [BACKPORT] Remove PR requirement from Changelog (#480)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#511 update regex for version bump
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#492 BigQuery_tests conversion
  tests/functional/test_changing_partitions.py
  tests/functional/test_hours_to_expiration.py
  tests/functional/test_location_change.py
  tests/integration/bigquery_test/adapter-specific-models/expiring_table.sql
  tests/integration/bigquery_test/location-models/model.sql
  tests/integration/bigquery_test/macros/partition_metadata.sql
  tests/integration/bigquery_test/partition-models/my_model.sql
  tests/integration/bigquery_test/partition-models/schema.yml
  tests/integration/bigquery_test/test_bigquery_adapter_specific.py
  tests/integration/bigquery_test/test_bigquery_location_change.py
Labels: cla:yes, Skip Changelog

#512 update prerelease -> prekind
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#502 [CI/CD] Backport release workflow to `1.4.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#501 [CI/CD] Backport release workflow to `1.3.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#500 [CI/CD] Backport release workflow to `1.2.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#513 Update requirements naming
  .github/workflows/main.yml
  .github/workflows/version-bump.yml
  CONTRIBUTING.md
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#499 [CI/CD] Backport release workflow to `1.1.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#509 convert test_store_test_failures to functional test
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
  tests/integration/store_test_failures_tests/models/fine_model.sql
  tests/integration/store_test_failures_tests/models/fine_model_but_with_a_no_good_very_long_name.sql
  tests/integration/store_test_failures_tests/models/problematic_model.sql
  tests/integration/store_test_failures_tests/models/schema.yml
  tests/integration/store_test_failures_tests/seeds/expected/expected_accepted_values.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_failing_test.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_not_null_problematic_model_id.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_unique_problematic_model_id.csv
  tests/integration/store_test_failures_tests/seeds/people.csv
  tests/integration/store_test_failures_tests/test_store_test_failures.py
  tests/integration/store_test_failures_tests/tests/failing_test.sql
  tests/integration/store_test_failures_tests/tests/passing_test.sql
Labels: cla:yes, Team:Adapters, Skip Changelog

#517 [CT-1966]: convert upload file test to a functional test
  tests/functional/adapter/upload_file_tests/data/csv/source.csv
  tests/functional/adapter/upload_file_tests/data/ndjson/source.ndjson
  tests/functional/adapter/upload_file_tests/data/parquet/source.parquet
  tests/functional/adapter/upload_file_tests/test_upload_file.py
  tests/integration/upload_file_tests/macros/upload_file.sql
  tests/integration/upload_file_tests/test_upload_file.py
Labels: cla:yes, Skip Changelog

#514 [CT-2030]: Convert simple seed to functional test
  tests/functional/adapter/test_simple_seed.py
  tests/integration/simple_seed_test/macros/schema_test.sql
  tests/integration/simple_seed_test/models-bq/schema.yml
  tests/integration/simple_seed_test/seeds-config/seed_configs.csv
  tests/integration/simple_seed_test/seeds-config/seed_disabled.csv
  tests/integration/simple_seed_test/seeds-config/seed_enabled.csv
  tests/integration/simple_seed_test/seeds-config/seed_tricky.csv
  tests/integration/simple_seed_test/test_seed_configs.py
Labels: cla:yes, Skip Changelog

#519 CT-1964/Remove the schema tests test
  tests/integration/schema_tests_test/models-v2/bq-models/ephemeral_copy.sql
  tests/integration/schema_tests_test/models-v2/bq-models/schema.yml
  tests/integration/schema_tests_test/models-v2/bq-models/table_summary.sql
  tests/integration/schema_tests_test/models-v2/seed/seed.csv
  tests/integration/schema_tests_test/test_schema_v2_tests.py
Labels: cla:yes, Skip Changelog

#227 Feature/merge exclude columns
  .changes/unreleased/Features-20220826-115320.yaml
  tests/functional/adapter/incremental/test_incremental_merge_exclude_columns.py
  tests/integration/simple_copy_test/test_simple_copy.py
Labels: cla:yes, ready_for_review, pr_tracked

#404 add dataset update lock
  .changes/unreleased/Fixes-20221213-102005.yaml
  dbt/adapters/bigquery/dataset.py
  dbt/adapters/bigquery/impl.py
  tests/functional/adapter/test_grant_access_to.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_dataset.py
Labels: cla:yes, Team:Adapters

#468 Rm defer_state_test
  tests/integration/defer_state_test/macros/infinite_macros.sql
  tests/integration/defer_state_test/macros/macros.sql
  tests/integration/defer_state_test/models/ephemeral_model.sql
  tests/integration/defer_state_test/models/exposures.yml
  tests/integration/defer_state_test/models/schema.yml
  tests/integration/defer_state_test/models/table_model.sql
  tests/integration/defer_state_test/models/view_model.sql
  tests/integration/defer_state_test/seeds/seed.csv
  tests/integration/defer_state_test/test_defer_state.py
Labels: cla:yes, Skip Changelog

#498 remove invocation of integration tests in tox
  .changes/unreleased/Under the Hood-20230130-170118.yaml
  CONTRIBUTING.md
  tox.ini
Labels: cla:yes, Team:Adapters

#518 parse vars in unit test utils
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#508 Sync Changelog team to GitHub team
  .bumpversion.cfg
  .changie.yaml
Labels: cla:yes, Skip Changelog

#532 specify 1.1 in batch runtime config
  .changes/unreleased/Fixes-20230213-203317.yaml
  dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes, backport 1.3.latest, backport 1.4.latest

#533 [CT-2092], [CT-2093]: test conversion for bigquery_test integration tests
  tests/functional/adapter/bigquery_test/fixtures.py
  tests/functional/adapter/bigquery_test/incremental_strategy_fixtures.py
  tests/functional/adapter/bigquery_test/seeds.py
  tests/functional/adapter/bigquery_test/test_incremental_strategies.py
  tests/functional/adapter/bigquery_test/test_simple_bigquery_view.py
  tests/integration/bigquery_test/adapter-models/schema.yml
  tests/integration/bigquery_test/adapter-models/source.sql
  tests/integration/bigquery_test/adapter-models/test_flattened_get_columns_in_table.sql
  tests/integration/bigquery_test/adapter-models/test_get_columns_in_table.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_merge_range.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_merge_time.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_overwrite_date.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_overwrite_day.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_overwrite_day_with_copy_partitions.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_overwrite_partitions.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_overwrite_range.sql
  tests/integration/bigquery_test/incremental-strategy-models/incremental_overwrite_time.sql
  tests/integration/bigquery_test/macros/test_creation.sql
  tests/integration/bigquery_test/macros/test_int_inference.sql
  tests/integration/bigquery_test/macros/test_project_for_job_id.sql
  tests/integration/bigquery_test/macros/wrapped_macros.sql
  tests/integration/bigquery_test/models/clustered_model.sql
  tests/integration/bigquery_test/models/fUnKyCaSe.sql
  tests/integration/bigquery_test/models/labeled_model.sql
  tests/integration/bigquery_test/models/multi_clustered_model.sql
  tests/integration/bigquery_test/models/partitioned_model.sql
  tests/integration/bigquery_test/models/schema.yml
  tests/integration/bigquery_test/models/sql_header_model.sql
  tests/integration/bigquery_test/models/sql_header_model_incr.sql
  tests/integration/bigquery_test/models/sql_header_model_incr_insert_overwrite.sql
  tests/integration/bigquery_test/models/sql_header_model_incr_insert_overwrite_static.sql
  tests/integration/bigquery_test/models/table_model.sql
  tests/integration/bigquery_test/models/view_model.sql
  tests/integration/bigquery_test/seeds/data_seed.csv
  tests/integration/bigquery_test/seeds/incremental_overwrite_date_expected.csv
  tests/integration/bigquery_test/seeds/incremental_overwrite_day_expected.csv
  tests/integration/bigquery_test/seeds/incremental_overwrite_range_expected.csv
  tests/integration/bigquery_test/seeds/incremental_overwrite_time_expected.csv
  tests/integration/bigquery_test/seeds/merge_expected.csv
  tests/integration/bigquery_test/test_incremental_strategies.py
  tests/integration/bigquery_test/test_simple_bigquery_view.py
Labels: cla:yes, Skip Changelog

#540 Python Test Clean Up
  tests/conftest.py
  tests/functional/adapter/test_python_model.py
  tox.ini
Labels: cla:yes, Skip Changelog

#426 dbt Constraints / model contracts
  .changes/unreleased/Features-20221220-193731.yaml
  dbt/include/bigquery/macros/adapters.sql
  dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
  dev-requirements.txt
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Team:Adapters

#525 Convert hook integration tests to functional
  tests/functional/adapter/hooks/data/seed_model.sql
  tests/functional/adapter/hooks/data/seed_run.sql
  tests/functional/adapter/hooks/test_model_hooks.py
  tests/functional/adapter/hooks/test_run_hooks.py
  tests/integration/hook_tests/macros/before-and-after-bq.sql
  tests/integration/hook_tests/macros/hook.sql
  tests/integration/hook_tests/models/hooks.sql
  tests/integration/hook_tests/seed-models-bq/schema.yml
  tests/integration/hook_tests/seeds/example_seed.csv
  tests/integration/hook_tests/test_model_hooks_bq.py
  tests/integration/hook_tests/test_run_hooks_bq.py
Labels: cla:yes, Skip Changelog

#545 Fix nightly release test
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  setup.py
Labels: cla:yes, Skip Changelog

#539 add new workflow for cutting .latest branches
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#423 Chenyu/remove manual retry
  .changes/unreleased/Under the Hood-20221209-161550.yaml
  dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes, ready_for_review, python_models, pr_tracked

#547 Fix nightly release test (#545)
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  setup.py
Labels: cla:yes, Skip Changelog

#554 Rename constraints_enabled to contract
  .changes/unreleased/Under the Hood-20230223-105149.yaml
  dbt/include/bigquery/macros/adapters.sql
Labels: cla:yes

#558 add codeowners file
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#541 mirror issues to ADAP jira project
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog

#565 Revert "mirror issues to ADAP jira project"
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes

#561 Ct 2183/setup tools distro info
  .dockerignore
  Makefile
  dev-requirements.txt
  docker_dev/README.md
  docker_dev/ubuntu.Dockerfile
  setup.py
Labels: cla:yes, Skip Changelog, backport 1.4.latest

#550 [Backport] 404
  .changes/unreleased/Fixes-20221213-102005.yaml
  dbt/adapters/bigquery/dataset.py
  dbt/adapters/bigquery/impl.py
  tests/functional/adapter/test_grant_access_to.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_dataset.py
Labels: cla:yes
