Repository dbt-labs/dbt-bigquery, pull requests merged in 2023-09, with the labels that each got.

#916 update expected values
  .changes/unreleased/Fixes-20230907-161347.yaml
  tests/functional/adapter/expected_stats.py
Labels: cla:yes

#902 Timeout BQ queries
  .changes/unreleased/Fixes-20230829-162111.yaml
  dbt/adapters/bigquery/connections.py
  tests/conftest.py
  tests/functional/test_job_timeout.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes

#919 quote column names in data types
  .changes/unreleased/Fixes-20230911-005506.yaml
  dbt/adapters/bigquery/column.py
  tests/functional/adapter/incremental/test_incremental_on_schema_change.py
Labels: cla:yes, ok to test, ready_for_review

#639 ADAP-400: Support materialized views with create/drop functionality
  .changes/unreleased/Features-20230330-165721.yaml
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/relation.py
  dbt/include/bigquery/macros/materializations/materialized_view.sql
  dbt/include/bigquery/macros/materializations/view.sql
  dbt/include/bigquery/macros/relations/drop.sql
  dbt/include/bigquery/macros/relations/materialized_view/_replace.sql
  dbt/include/bigquery/macros/relations/materialized_view/alter.sql
  dbt/include/bigquery/macros/relations/materialized_view/create.sql
  dbt/include/bigquery/macros/relations/materialized_view/drop.sql
  dbt/include/bigquery/macros/relations/materialized_view/refresh.sql
  dbt/include/bigquery/macros/relations/table/drop.sql
  dbt/include/bigquery/macros/relations/table/rename.sql
  dbt/include/bigquery/macros/relations/view/drop.sql
  dbt/include/bigquery/macros/relations/view/rename.sql
  dbt/include/bigquery/macros/relations/view/replace.sql
  tests/functional/adapter/materialized_view_tests/test_materialized_view.py
  tests/functional/adapter/materialized_view_tests/utils.py
Labels: cla:yes

#933 Address type annotation issues and clean up impl
  .changes/unreleased/Under the Hood-20230921-155645.yaml
  .changes/unreleased/Under the Hood-20230922-125327.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/impl.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes

#936 Update SQLQuery to include node_info
  .changes/unreleased/Under the Hood-20230922-114217.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#944 automate repo cleanup
  .github/workflows/repository-cleanup.yml
Labels: cla:yes, Skip Changelog

#942 [Backport] Fix contact validation failure on query data types change (#862)
  .changes/unreleased/Fixes-20230804-005817.yaml
  dbt/include/bigquery/macros/adapters/columns.sql
Labels: cla:yes

#929 poll `.GetBatch()` instead of using `operation.result()`
  .changes/unreleased/Fixes-20230721-101041.yaml
  .github/workflows/integration.yml
  dbt/adapters/bigquery/dataproc/__init__.py
  dbt/adapters/bigquery/dataproc/batch.py
  dbt/adapters/bigquery/python_submissions.py
  tests/functional/adapter/test_python_model.py
  tests/unit/test_configure_dataproc_batch.py
Labels: cla:yes

#927 Add dbt show tests
  .changes/unreleased/Under the Hood-20230925-143628.yaml
  dev-requirements.txt
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes

#945 fix mistaken dev-requirements change
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#947 [Backport] 927 and fix core pointer
  .changes/unreleased/Under the Hood-20230925-143628.yaml
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes, Skip Changelog

#946 [Backport] pr 927 and fix core pointer
  .changes/unreleased/Under the Hood-20230925-143628.yaml
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes, Skip Changelog
