Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-11, with the labels that each got.

#1345 Feature/add quota project option
  .changes/unreleased/Features-20240911-234859.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/test_quota_project.py
  tests/unit/test_bigquery_adapter.py
Labels: cla:yes, ok to test, user docs, community

#1394 Update macos runners from macos-12 to macos-14
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1391 Break out credentials as a separate module
  .changes/unreleased/Under the Hood-20241104-173815.yaml
  dbt/adapters/bigquery/__init__.py
  dbt/adapters/bigquery/column.py
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/credentials.py
  dbt/adapters/bigquery/dataproc/batch.py
  dbt/adapters/bigquery/dataset.py
  dbt/adapters/bigquery/gcloud.py
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/adapters/bigquery/relation.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_configure_dataproc_batch.py
Labels: cla:yes

#1398 update macos runners from macos-12 to macos-14 (#1394)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1400 update macos runners from macos-12 to macos-14 (#1394)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1401 update macos runners from macos-12 to macos-14 (#1394)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1402 update macos runners from macos-12 to macos-14 (#1394)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1395 Add retry factory to consolidate retry strategies across dbt-bigquery
  .changes/unreleased/Under the Hood-20241107-143856.yaml
  dbt/adapters/bigquery/clients.py
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/credentials.py
  dbt/adapters/bigquery/dataproc/__init__.py
  dbt/adapters/bigquery/dataproc/batch.py
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/adapters/bigquery/retry.py
  dbt/adapters/bigquery/utility.py
  tests/conftest.py
  tests/functional/adapter/test_json_keyfile.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_bigquery_connection_manager.py
  tests/unit/test_configure_dataproc_batch.py
Labels: cla:yes
