Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-06, with the labels that each got.

#1245 Allow base64-service-account-json key auth Issue: #923
  .changes/unreleased/Features-20240516-125735.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/utility.py
  tests/conftest.py
  tests/functional/adapter/test_json_keyfile.py
Labels: cla:yes, ok to test, user docs

#1254 Suppress warning about 'bad type'.
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, Skip Changelog

#1257 Forward-port fix from #1085
  .changes/unreleased/Fixes-20240201-145323.yaml
  dbt/include/bigquery/macros/catalog/catalog.sql
Labels: cla:yes, backport 1.8.latest

#1250 Adap 1162/merge agate lazy load
  .changes/unreleased/Under the Hood-20240331-101418.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/relation_configs/_base.py
Labels: cla:yes

#1263 Update internal release naming and arguments
  .github/workflows/release-internal.yml
Labels: cla:yes, Skip Changelog
