Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-05, with the labels that each got.

#1225 Add missing changelog backlinks.
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#1205 Add configuration options for `enable_list_inference` and `intermediate_format` for python models
  .changes/unreleased/Features-20240426-105319.yaml
  .changes/unreleased/Fixes-20240426-105224.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/materializations/table.sql
  tests/functional/python_model_tests/__init__.py
  tests/functional/python_model_tests/files.py
  tests/functional/python_model_tests/test_list_inference.py
Labels: cla:yes

#1226 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Skip Changelog

#1229 update TestListInference to TestPythonListInference
  tests/functional/python_model_tests/test_list_inference.py
Labels: cla:yes, Skip Changelog

#1122 implement choice of delimiter for seed files
  .changes/unreleased/Fixes-20240226-233024.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/materializations/seed.sql
  tests/functional/adapter/test_simple_seed.py
Labels: cla:yes, ready_for_review

#1233 remove dependency on dbt-core legacy logger
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes, Skip Changelog

#1219 Cross-database `date` macro
  .changes/unreleased/Features-20240501-151902.yaml
  dbt/include/bigquery/macros/utils/date.sql
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#1215 Import relevant pytest(s) for cross-database `cast` macro
  .changes/unreleased/Features-20240430-185650.yaml
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#1235 Bump deps on common, adapters, core
  setup.py
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#1241 fix Core version bump in setup.py during release
  .bumpversion.cfg
  setup.py
Labels: cla:yes, Skip Changelog

#1242 backport 1241 to 1.8.latest
  .bumpversion.cfg
  setup.py
Labels: cla:yes

#1170 Add docker release to the full release process for final releases
  .github/dependabot.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  Makefile
  docker/Dockerfile
  docker/README.md
  docker/dev.Dockerfile
  docker_dev/README.md
  docker_dev/ubuntu.Dockerfile
Labels: cla:yes, Skip Changelog
