Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-12, with the labels that each got.

#1420 update libpq-dev dependency to 13.18-0+deb11u1
  docker/Dockerfile
Labels: cla:yes, Skip Changelog

#1423 Remove custom retry in get_table call
  .changes/unreleased/Fixes-20241205-133606.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#1422 Fix: Cast to timestamp prior to event time comparison
  .changes/unreleased/Fixes-20241204-105846.yaml
  dbt/adapters/bigquery/relation.py
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/test_incremental_microbatch.py
Labels: cla:yes, backport 1.9.latest

#1426 Backport 1423 to 1.9.latest
  .changes/unreleased/Fixes-20241205-133606.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#1421 [Feature] Allow `copy_partitions` when using `microbatch`
  .changes/unreleased/Features-20241202-223835.yaml
  dbt/include/bigquery/macros/materializations/incremental.sql
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/test_incremental_microbatch.py
Labels: cla:yes, ok to test, backport 1.9.latest

#1407 ADAP-1116: Move to `hatch` and `pyproject.toml`
  .bumpversion.cfg
  .changes/unreleased/Under the Hood-20241117-194746.yaml
  .github/scripts/env-setup.sh
  .github/scripts/update_dependencies.sh
  .github/scripts/update_dev_dependency_branches.sh
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  .github/workflows/release_prep_hatch.yml
  .github/workflows/version-bump.yml
  MANIFEST.in
  Makefile
  dev-requirements.txt
  hatch.toml
  mypy.ini
  pyproject.toml
  pytest.ini
  scripts/build-dist.sh
  setup.py
  tox.ini
Labels: cla:yes

#1433 Update the pytest timeout from 10min to 15min for python tests
  tox.ini
Labels: Skip Changelog

#1435 Update the default inputs on the integration tests workflow to match the branch
  .github/workflows/integration.yml
Labels: Skip Changelog

#1431 [Bug] Use bigquery default retryable exceptions
  .changes/unreleased/Fixes-20241211-144752.yaml
  dbt/adapters/bigquery/retry.py
  tests/unit/test_bigquery_connection_manager.py
Labels: bug, cla:yes

#1408 Retry on 503
  .changes/unreleased/Fixes-20241120-163101.yaml
  dbt/adapters/bigquery/clients.py
  dbt/adapters/bigquery/retry.py
  hatch.toml
Labels: cla:yes
