Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-02, with the labels that each got.

#1085 Fix null column index issue during `dbt docs generate` for external tables
  .changes/unreleased/Fixes-20240201-145323.yaml
  dbt/include/bigquery/macros/catalog/catalog.sql
Labels: cla:yes

#1083 [Backport 1.5.latest] Fix contract validation failure on query data types change
  .changes/unreleased/Fixes-20230804-005817.yaml
  dbt/include/bigquery/macros/adapters/columns.sql
Labels: support

#1082 Add dbt-core install back to dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#1095 Remove actions that sync github and jira
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog, support

#1100 Use dbt-common main in dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#1031 [Bigquery] unit test tests + support for complex types
  .changes/unreleased/Features-20240205-174614.yaml
  dbt/include/bigquery/macros/utils/safe_cast.sql
  tests/functional/adapter/unit_testing/test_unit_testing.py
Labels: cla:yes

#1063 Implement relation filtering on get_catalog macro
  .changes/unreleased/Features-20231219-201203.yaml
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/relation_configs/_partition.py
  dbt/include/bigquery/macros/catalog.sql
  dbt/include/bigquery/macros/catalog/by_relation.sql
  dbt/include/bigquery/macros/catalog/by_schema.sql
  dbt/include/bigquery/macros/catalog/catalog.sql
Labels: cla:yes

#986 Fix merge fails when partition is required
  .changes/unreleased/Fixes-20231105-143145.yaml
  dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql
  dbt/include/bigquery/macros/materializations/incremental_strategy/merge.sql
  tests/functional/adapter/incremental/incremental_strategy_fixtures.py
  tests/functional/adapter/incremental/test_incremental_strategies.py
Labels: cla:yes, ok to test

#1105 Remove refresh token field from connection keys
  .changes/unreleased/Fixes-20240216-133319.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#1061 remove _json_from_json patch
  .changes/unreleased/Fixes-20231219-153446.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes

#1109 Remove custom query job async timeout logic
  .changes/unreleased/Fixes-20240219-103324.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/test_job_timeout.py
  tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes

#1112 Remove custom query job async timeout logic (#1109)
  .changes/unreleased/Fixes-20240219-103324.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/test_job_timeout.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes

#1111 Remove custom query job async timeout logic (#1109)
  .changes/unreleased/Fixes-20240219-103324.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/test_job_timeout.py
  tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes

#1128 update dbt-common dependency to <2.0
  setup.py
Labels: cla:yes, Skip Changelog
