Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-07, with the labels that each got.

#1266 Base 207/add test
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes, Skip Changelog

#1285 Swap the order of the sdist and wheel checks
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1287 [Backport 1.2.latest] Swap the order of the sdist and wheel checks (#1285)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1288 [Backport 1.1.latest] Swap the order of the sdist and wheel checks (#1285)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1289 [Backport 1.0.latest] Swap the order of the sdist and wheel checks (#1285)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1076 ADAP-1051 - Temp Table Drop Fix
  .changes/unreleased/Fixes-20240120-180818.yaml
  dbt/include/bigquery/macros/materializations/incremental.sql
  tests/functional/test_drop_temp_relation.py
Labels: cla:yes, ok to test, test all, ready_for_review, support

#1296 Make `dependabot` ignore patch updates
  .github/dependabot.yml
Labels: cla:yes, Skip Changelog

#1291 Move code quality deps to precommit
  .changes/unreleased/Under the Hood-20240718-193206.yaml
  .flake8
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  dbt/adapters/bigquery/__init__.py
  dbt/adapters/bigquery/column.py
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/dataproc/batch.py
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/adapters/bigquery/relation.py
  dbt/adapters/bigquery/relation_configs/_base.py
  dbt/adapters/bigquery/relation_configs/_cluster.py
  dbt/adapters/bigquery/relation_configs/_materialized_view.py
  dbt/adapters/bigquery/relation_configs/_options.py
  dbt/adapters/bigquery/relation_configs/_partition.py
  dev-requirements.txt
  mypy.ini
  tests/functional/python_model_tests/test_list_inference.py
  tests/unit/utils.py
Labels: cla:yes

#1308 constraints update causing test failures in ci/cd
  dev-requirements.txt
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes, Skip Changelog
