Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-03, with the labels that each got.

#1130 allow for pre-release common/adapters
  setup.py
Labels: cla:yes, Skip Changelog

#1132 Fix wheel/sdist check
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1141 Test ddtrace dependency range
  .changes/unreleased/Dependencies-20240319-102258.yaml
  dev-requirements.txt
Labels: cla:yes

#1140 Add Bigquery internal build process workflow
  .changes/unreleased/Features-20240318-032256.yaml
  .github/workflows/release-internal.yml
Labels: cla:yes

#1125 Fix the renamed relations code
  .changes/unreleased/Under the Hood-20240227-004659.yaml
  dbt/adapters/bigquery/relation.py
  tests/unit/test_renamed_relations.py
Labels: cla:yes

#1147 remove `keyfile` from `_connection_keys`
  .changes/unreleased/Fixes-20240322-113720.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, backport 1.6.latest, backport 1.7.latest

#1143 Finish internal build workflow
  .github/workflows/release-internal.yml
Labels: cla:yes, Skip Changelog

#1153 Add `pandas` extra for `google-cloud-bigquery` to pick up missing `pyarrow`
  .changes/unreleased/Fixes-20240327-210249.yaml
  setup.py
Labels: cla:yes, test all, backport 1.4.latest, backport 1.5.latest, backport 1.6.latest, backport 1.7.latest

#1156 Add `pandas` extra for `google-cloud-bigquery` to pick up missing `py…
  .changes/unreleased/Fixes-20240327-210249.yaml
  setup.py
Labels: cla:yes

#1155 Add `pandas` extra for `google-cloud-bigquery` to pick up missing `py…
  .changes/unreleased/Fixes-20240327-210249.yaml
  setup.py
Labels: cla:yes

#1154 Add `pandas` extra for `google-cloud-bigquery` to pick up missing `py…
  .changes/unreleased/Fixes-20240327-210249.yaml
  setup.py
Labels: cla:yes

#1151 Pin `black>=24.3`
  .changes/unreleased/Security-20240327-193211.yaml
  dev-requirements.txt
Labels: cla:yes
