Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-10, with the labels that each got.

#1360 Catch google `NotFound` exception as a `DbtDatabaseError`
  .changes/unreleased/Fixes-20241001-193207.yaml
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#1373 Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-185117.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  dev-requirements.txt
  docker/Dockerfile
  docker/dev.Dockerfile
  setup.py
  tox.ini
Labels: cla:yes

#1346 Isolating distribution testing
  .changes/unreleased/Under the Hood-20240910-212052.yaml
  .github/workflows/main.yml
Labels: cla:yes, ok to test

#1375 Add matrix entry back that was inadvertently removed during a sync with main
  .github/workflows/main.yml
Labels: Skip Changelog

#1357 Replace 'integration' with 'functional' in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla:yes, ok to test, Skip Changelog

#1379 [Backport 1.8.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-185117.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1381 [Backport 1.7.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-185117.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1382 [Backport 1.6.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-185117.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1384 [Backport 1.4.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-185117.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1383 [Backport 1.5.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-185117.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1380 backport 1122 to 1.8.latest
  .changes/unreleased/Fixes-20240226-233024.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/materializations/seed.sql
  tests/functional/adapter/test_simple_seed.py
Labels: cla:yes

#1224 add test case when raise ServiceUnavailable in is_retryable
  .changes/unreleased/Features-20240505-011838.yaml
  tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes, ok to test

#1388 use "direct" write for non-partitioned python model materializations
  .changes/unreleased/Fixes-20241028-172719.yaml
  dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes
