Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-01, with the labels that each got.

#1026 feature/decouple adapters from core
  .changes/unreleased/Features-20240102-152030.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/dataset.py
  dbt/adapters/bigquery/gcloud.py
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/python_submissions.py
  dbt/adapters/bigquery/relation.py
  dbt/adapters/bigquery/relation_configs/_base.py
  dbt/adapters/bigquery/relation_configs/_cluster.py
  dbt/adapters/bigquery/relation_configs/_materialized_view.py
  dbt/adapters/bigquery/relation_configs/_options.py
  dbt/adapters/bigquery/relation_configs/_partition.py
  dbt/adapters/bigquery/utility.py
  dbt/include/bigquery/macros/relations/materialized_view/alter.sql
  dbt/include/bigquery/macros/relations/materialized_view/create.sql
  dbt/include/bigquery/macros/relations/materialized_view/replace.sql
  dev-requirements.txt
  tests/functional/adapter/describe_relation/test_describe_relation.py
  tests/functional/adapter/materialized_view_tests/_mixin.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_bigquery_connection_manager.py
  tests/unit/utils.py
  tox.ini
Labels: cla:yes

#1074 1.7.latest remove _json_from_json patch
  .changes/unreleased/Fixes-20231219-153446.yaml
  dbt/adapters/bigquery/connections.py
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes

#1072 Implementation of metadata-based freshness
  .changes/unreleased/Features-20231218-155409.yaml
  dbt/adapters/bigquery/impl.py
  tests/boundary/test_bigquery_sdk.py
  tests/functional/adapter/sources_freshness_tests/files.py
  tests/functional/adapter/sources_freshness_tests/test_get_relation_last_modified.py
Labels: cla:yes

#1073 Implement relation filtering on get_catalog macro
  .changes/unreleased/Features-20231219-201203.yaml
  dbt/adapters/bigquery/impl.py
  dbt/include/bigquery/macros/catalog.sql
  dbt/include/bigquery/macros/catalog/by_relation.sql
  dbt/include/bigquery/macros/catalog/by_schema.sql
  dbt/include/bigquery/macros/catalog/catalog.sql
Labels: cla:yes

#1075 add TableLastModifiedMetadata capability enum to impl and specify timeout
  dbt/adapters/bigquery/impl.py
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#1071 Migrate to dbt-adapter and common
  .changes/unreleased/Under the Hood-20240116-154305.yaml
  dbt/adapters/bigquery/connections.py
  dbt/adapters/bigquery/gcloud.py
  dbt/adapters/bigquery/impl.py
  dbt/adapters/bigquery/relation.py
  dbt/adapters/bigquery/relation_configs/_partition.py
  dbt/adapters/bigquery/utility.py
  setup.py
  tests/functional/adapter/column_types/fixtures.py
  tests/functional/adapter/test_aliases.py
  tests/unit/test_bigquery_adapter.py
  tests/unit/test_bigquery_connection_manager.py
  tests/unit/utils.py
Labels: cla:yes

#1019 Primary and foreign key constraints are not enforced in BigQuery
  .changes/unreleased/Under the Hood-20231116-062142.yaml
  dbt/adapters/bigquery/impl.py
Labels: cla:yes, ready_for_review, support

#1077 update dev-requirements.txt to use dbt-adapters for dbt-tests-adapter
  .changes/unreleased/Dependencies-20240124-120321.yaml
  dev-requirements.txt
  setup.py
Labels: cla:yes

#1078 [Backport 1.7.latest] Fix configuration change monitoring for scenarios with no changes (#1009)
  .changes/unreleased/Fixes-20231107-174352.yaml
  dbt/adapters/bigquery/relation.py
  dbt/adapters/bigquery/relation_configs/_partition.py
  tests/functional/adapter/materialized_view_tests/_files.py
  tests/functional/adapter/materialized_view_tests/test_materialized_view.py
Labels: cla:yes, support
