Repository dbt-labs/dbt-bigquery, pull requests merged in 2024-04, with the labels that each got.

#1165 [Backport 1.2.latest] Test ddtrace dependency range (#1141)
  .changes/unreleased/Dependencies-20240319-102258.yaml
  dev-requirements.txt
Labels: cla:yes

#1164 [Backport 1.3.latest] Test ddtrace dependency range (#1141)
  .changes/unreleased/Dependencies-20240319-102258.yaml
  dev-requirements.txt
Labels: cla:yes

#1168 Add `dbt-core~=1.8.0a1` as convenience dep
  .changes/unreleased/Dependencies-20240403-134956.yaml
  setup.py
Labels: cla:yes

#1176 Update dependabot config to cover GHA
  .changes/unreleased/Under the Hood-20240410-182121.yaml
  .github/dependabot.yml
Labels: cla:yes

#1089 Create BQ version of string_literal with correct quoting
  .changes/unreleased/Fixes-20240205-102954.yaml
  dbt/include/bigquery/macros/utils/string_literal.sql
  tests/functional/adapter/test_string_literal_macro.py
Labels: cla:yes, ready_for_review

#1188 Add pre-commit check for dbt-core
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog

#1194 Preserve nicely formatted timeout exception (#1187)
  dbt/adapters/bigquery/connections.py
Labels: cla:yes, Skip Changelog

#1193 backport 1187 to 1.6.latest
  dbt/adapters/bigquery/connections.py
Labels: cla:yes

#1190 Stop adding aliases to render_limited output
  .changes/unreleased/Fixes-20240423-131752.yaml
  dbt/adapters/bigquery/relation.py
  tests/functional/adapter/empty/test_empty.py
Labels: cla:yes

#1195 Pin `macos` test runners to `macos-12`
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1201 [Backport 1.2.latest] Pin `macos` runners to `macos-12` (#1195)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1200 [Backport 1.3.latest] Pin `macos` runners to `macos-12` (#1195)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1199 [Backport 1.4.latest] Pin `macos` runners to `macos-12` (#1195)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1198 [Backport 1.5.latest] Pin `macos` runners to `macos-12` (#1195)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1197 [Backport 1.6.latest] Pin `macos` runners to `macos-12` (#1195)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1196 [Backport 1.7.latest] Pin `macos` runners to `macos-12` (#1195)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1203 [Backport 1.0.latest] Pin `macos` runners to `macos-12` (#1195)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog
