Repository dbt-labs/dbt-bigquery, pull requests merged in 2025-01, with the labels that each got.

#1445 Retry on 503 (#1408)
  .changes/unreleased/Fixes-20241120-163101.yaml
  dbt/adapters/bigquery/clients.py
  dbt/adapters/bigquery/retry.py
Labels: cla:yes

#1449 Update upload artifacts 1.4
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#1448 Update upload artifacts 1.5
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#1450 Update upload artifacts 1.6
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#1451 Update upload artifacts 1.7
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#1452 Update upload artifacts 1.8
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#1453 Remove the artifacts related workflow steps
  .github/workflows/main.yml
Labels: cla:yes

#1454 Remove artifacts steps 1.5
  .github/workflows/main.yml
Labels: cla:yes

#1456 Remove the artifacts related workflow steps
  .github/workflows/main.yml
Labels: cla:yes

#1457 Remove the artifacts related workflow steps
  .github/workflows/main.yml
Labels: cla:yes

#1459 ADAP-1135: Update dbt-adapters ref to point to the subdirectory
  dev-requirements.txt
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#1460 [Backport 1.8.latest] Update dbt-adapters ref to point to the subdirectory
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#1461 Combine build verification jobs to avoid needing to upload and download artifacts
  .github/workflows/main.yml
Labels: Skip Changelog, backport 1.8.latest, backport 1.7.latest
